### ISSUE TITLE
try okteto its free

### ISSUE THREAD

**Issue by rishabhmodi03** [yash-dk/TorToolkit-Telegram#113]
you should try okteto also as it provide services for free.and docker also works

**Comment by AmirulAndalib** [comment]
> you should try okteto also as it provide services for free.and docker also works

# you stupid Stop abusing free stuff

**Comment by rishabhmodi03** [comment]
i am only giving a suggestion

**Comment by rishabhmodi03** [comment]
we should not harm resources....... As we all know miners has already destroyed so much resources of the use only for good purpose
