### ISSUE TITLE
(Enhancement Request) YT Links Only Gets Leeched To Telegram

### ISSUE THREAD

**Issue by iamLiquidX** [yash-dk/TorToolkit-Telegram#22]
Yt Links Only Gets Leeched To Telegram Even When Telegram Leeched Is Disabled.

**Comment by yash-dk** [comment]
It's not a bug, but I will get that feature soon.

**Comment by iamLiquidX** [comment]
I just created this to help you keep track 😊, as u said in grp

**Comment by yash-dk** [comment]
> I just created this to help you keep track 😊, as u said in grp

Ohkk 😅 👍👍

**Comment by yash-dk** [comment]
Check the latest BETA version its added.

**Comment by iamLiquidX** [comment]
Ok ,i will close this. Will check right away.

**Comment by yash-dk** [comment]
> Ok ,i will close this. Will check right away.

Thanks Let me know the same if it works or not....

**Comment by iamLiquidX** [comment]
> > Ok ,i will close this. Will check right away.
> 
> Thanks Let me know the same if it works or not....

All good ....
