### ISSUE TITLE
Rename files before leech

### ISSUE THREAD

**Issue by yasirarism** [yash-dk/TorToolkit-Telegram#26]

**Comment by FristyFlakes** [comment]
Needed For Direct Links. Should've Been Implemented By Now

**Comment by yash-dk** [comment]
> Needed For Direct Links. Should've Been Implemented By Now

Afk for a while will do it asap when back.

**Comment by FristyFlakes** [comment]
> > Needed For Direct Links. Should've Been Implemented By Now
> 
> Afk for a while will do it asap when back.

Roger That.

**Comment by yash-dk** [comment]
Added in the format of `/leech you file name.extension` only supported for direct links.
