### ISSUE TITLE
RCLONE_BASE_DIR problem

### ISSUE THREAD

**Issue by 547555909** [yash-dk/TorToolkit-Telegram#43]
I change the RCLONE_BASE_DIR：RCLONE_BASE_DIR = "Gdrive"
and docker-compose up again.
but the files still upload to GOOGLE DRIVE root folder
![image](https://user-images.githubusercontent.com/19320063/111727460-e4878480-88a5-11eb-8b48-37dba1d128c6.png)

**Comment by vpn12** [comment]
It would be like this,
RCLONE_BASE_DIR = "/Gdrive/"

Working fine for me.

**Comment by 547555909** [comment]
> It would be like this,
> RCLONE_BASE_DIR = "/Gdrive/"
> 
> Working fine for me.

I try it，thank you bro！

**Comment by yourtulloh** [comment]
Done? Then Close this issue

**Comment by yash-dk** [comment]
I think it's done....

**Comment by 547555909** [comment]
> I think it's done....

not work,i was setting my rclone.conf by telegram
![image](https://user-images.githubusercontent.com/19320063/112799386-da813500-90a0-11eb-8a90-76014bb73b42.png)
Then i edit the RCLONE_BASE_DIR :/Grive/,it still upload the root folder

**Comment by 547555909** [comment]
Solved
