### ISSUE TITLE
Hey heroku deploy repo please

### ISSUE THREAD

**Issue by sunilroy007** [yash-dk/TorToolkit-Telegram#59]
i got old repo on heroku deploy but its not renaming files and cant leech folders need new repo please

**Comment by reaitten** [comment]
no

**Comment by sunilroy007** [comment]
> no

Yes

**Comment by sunilroy007** [comment]
People using this new repo and modifies something so heroku wont bann... If anyone know please tell or i will stick with old repo

**Comment by BlackStoneReborn** [comment]
You're free to use the code for anything you want - if you know what you're doing.

There will be no Deploy-Button, there won't come one.

**Comment by sunilroy007** [comment]
> You're free to use the code for anything you want - if you know what you're doing.
> 
> There will be no Deploy-Button, there won't come one.

if i know that i wont be asking here bro.... why wont their be heroku deploy? if anyone know how to modify repo to deploy in heroku please give me in private

**Comment by aaryanmishra** [comment]
I deployed my own leech bot

It's in python

Can you give me heroku.yml Code pls

**Comment by aaryanmishra** [comment]
> > I deployed my own leech bot
> > It's in python
> > Can you give me heroku.yml Code pls
> 
> if you can help me in deploying to heroku i can... i had old repo with heroku support(heroku.yml) but just need to know how to make this new repo compatible with heroku.. if you know contact me in telegram @sunilroy007

No need

**Comment by yash-dk** [comment]
check https://t.me/ttkdisc
