### ISSUE TITLE
Issue On cancelling big files

### ISSUE THREAD

**Issue by noonegupta734** [yash-dk/TorToolkit-Telegram#7]
`2021-01-17 23:34:53,499 ERROR MainThread telethon.client.updates Unhandled exception on callback_handler_canc
Traceback (most recent call last):
   File "/usr/local/lib/python3.8/dist-packages/telethon/client/updates.py", line 446, in _dispatch_update
     await callback(event)
   File "/torapp/tortoolkit/core/HandleManager.py", line 402, in callback_handler_canc
     if data[2] == str(e.sender_id):
 IndexError: list index out of range`

This is the error on trying to cancel this torrent

**Comment by yash-dk** [comment]
Can you leave the magnet maybe?

**Comment by noonegupta734** [comment]
> Can you leave the magnet maybe?

Sent u on telegram sizes greater than 100gb cant be cancelled

**Comment by noonegupta734** [comment]
Any update on this when it will be fixed !!

**Comment by yash-dk** [comment]
Fixed
