### ISSUE TITLE
[FEATURE REQUEST] Append predefined trackers from tracker list in Torrent/Magnet Downloads to speed things up

### ISSUE THREAD

**Issue by rokibhasansagar** [yash-dk/TorToolkit-Telegram#76]
To put this simply,
when a user provides a magnet link with 3/4 trackers, the files are downloaded slowly.

But if the user would supply more live trackers appended onto the magnet link, the download would be faster as more tracker means more active peers connected.

Any BitTorrent client GUI can add separate trackers manually, and Aria2 can also load extra trackers through an extra tracker list file.

Maybe same result can be achieved through qbittorrent(-nox) api.

I don't know how to, but it can surely be done.

**Comment by noobalphamax** [comment]
Yes, same suggestion. In the desktop client adding extra set of trackers and updating list enhances the speed and was very much useful for some slow torrents which are sometimes the only source available. This feature request will be a better thing to implement. 


Hats off to your wonderful work, integrating maximum things.

**Comment by rokibhasansagar** [comment]
I see it's not exactly implemented in "Alpha" till I'm writing this.

I got a guide on How to implement it, but you know better about How to code this.

There's a reference about adding extra trackers once a torrent is loaded through `qbittorrentapi.torrents.TorrentsAPIMixIn` class in "qbittorrent-api" pip package.

>`torrents_add_trackers(torrent_hash=None, urls=None, **kwargs)`

You can read it here:
https://qbittorrent-api.readthedocs.io/en/latest/apidoc/torrents.html#qbittorrentapi.torrents.TorrentsAPIMixIn.torrents_add_trackers

And the extra torrent tracker parameter, namely `urls` might be in `tracker01&tr=tracker02&tr=tracker03` format, I don't know for sure.

There are two frequently updated (two newline delimited) tracker list available to use here (after proper single-line formatting).
> https://ngosang.github.io/trackerslist/trackers_best.txt
> https://newtrackon.com/api/stable

I'm hoping to see this feature properly added when all the bug-fix are done in next stable release.
😃

**Comment by afjal-sharif** [comment]
Its already added on slam mirror bot....

**Comment by rokibhasansagar** [comment]
> Its already added on slam mirror bot....

I know, man!
As TTK downloads Torrents, this feature is crucial for faster downloads.
Otherwise, users will use same old Mirror-Bots 😞

**Comment by afjal-sharif** [comment]
Right...i think dev will implement it on next update... 👌

**Comment by yash-dk** [comment]
Support for custom trackers is added you can change the source of the trackers from ExecVars if you wish to and Enable/Disable adding custom trackers.
