### ISSUE TITLE
YTDL Button 🔘 Not working

### ISSUE THREAD

**Issue by MrBotDeveloper** [yash-dk/TorToolkit-Telegram#77]
While using the ytdl button for the Quality Selection and when we try to back and change quality it doesn't go back....

So please fix it...

**Comment by yash-dk** [comment]
Has been fixed [here](https://github.com/yash-dk/TorToolkit-Telegram/commit/5a8f36d07cedb5f8f77f63dc50c06000c62c7c47) beta branch.
