### ISSUE TITLE
Bot doesn't sent logs on it's command... 

### ISSUE THREAD

**Issue by MrBotDeveloper** [yash-dk/TorToolkit-Telegram#81]
Sir, the bot is not doesn't sent the log file on it's command on sending the command it only delete the command ..... Please fix it...

**Comment by devcloudd** [comment]
> Sir, the bot is not doesn't sent the log file on it's command on sending the command it only delete the command ..... Please fix it...

**Comment by MrBotDeveloper** [comment]
@yash-dk please respond

**Comment by dishapatel010** [comment]
> @yash-dk please respond

where deployed ?

**Comment by MrBotDeveloper** [comment]
Heroku

**Comment by MrBotDeveloper** [comment]
Heroku

**Comment by dishapatel010** [comment]
> Heroku

Haha it won't gona work for heroku

**Comment by MrBotDeveloper** [comment]
🧐
