### ISSUE TITLE
[Feature Request] Youtube-dl add multiple links

### ISSUE THREAD

**Issue by junevm** [yash-dk/TorToolkit-Telegram#82]
Ability to download multiple links from youtube-dl supported site.

Say I want to to download 10 videos in single command.
Example command

/ytdl link1,link2,link3 and so on
And it will sequentiality download one by one or multiple at once

Also when is Service Account support coming? @yash-dk

**Comment by yash-dk** [comment]
SA support is added in the new Alpha version will be released in 2nd week of Aug. Join https://t.me/ttkdisc as I am afk for a period.

Will look into the YTDL one ....

**Comment by junevm** [comment]
another way can be that I put all the ytdl supported URLs that I want to download in a text file and send it to the bot. The bot downloads each URL sequentially from text file using ytdl.
